test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

selectel:
  service: S3
  bucket: <%= ENV['S3_BUCKET'] %>
  endpoint: 'https://s3.storage.selcloud.ru'
  access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['S3_SECRET_ACCESS_KEY'] %>
  region: ru-1